using Microsoft.EntityFrameworkCore;

namespace GreatestFilms.Models
{
    public class FilmContext:DbContext
    {
        public DbSet<Film> Films { get; set; }
        public FilmContext(DbContextOptions<FilmContext> options) : base(options)
        {
            if(Database.EnsureCreated())
            {
                Films.Add(new Film { Name="Atlantis: The Lost Empire", DirectorName= "Gary Trousdale", Genre="Action-Adventure", Poster="~/Images/Atlantis.jpg", Date="2001", Description="Atlantis: The Lost Empire is a 2001 American animated science fiction action-adventure film produced by Walt Disney Feature Animation and released by Walt Disney Pictures. It was directed by Gary Trousdale and Kirk Wise and produced by Don Hahn, from a screenplay by Tab Murphy, and a story by Murphy, Wise, Trousdale, Joss Whedon, and the writing team of Bryce and Jackie Zabel." });
                Films.Add(new Film { Name="Blade Runner: 2049", DirectorName= "Denis Villeneuve", Genre="Science Fiction", Poster="~/Images/BladeRunner2049.jpg", Date="2017", Description="Blade Runner 2049 is a 2017 American epic neo-noir science fiction film directed by Denis Villeneuve and written by Hampton Fancher and Michael Green.[10] A sequel to the 1982 film Blade Runner, the film stars Ryan Gosling and Harrison Ford, with Ana de Armas, Sylvia Hoeks, Robin Wright, Mackenzie Davis, Dave Bautista, and Jared Leto in supporting roles. Ford and Edward James Olmos reprise their roles from the original film."});
                Films.Add(new Film { Name="Dead Poets Society", DirectorName= "Peter Weir", Genre="Drama", Poster="~/Images/DeadPoetsSociety.jpg", Date="1989", Description="Dead Poets Society is a 1989 American coming-of-age drama film directed by Peter Weir and written by Tom Schulman. The film, starring Robin Williams, is set in 1959 at the fictional elite boarding school Welton Academy, and tells the story of an English teacher who inspires his students through his teaching of poetry." });
                Films.Add(new Film { Name="Highlander", DirectorName= "Russell Mulcahy", Genre="Action-Adventure", Poster="~/Images/Highlander.jpg", Date= "1986", Description= "Highlander is a 1986 fantasy action-adventure film directed by Russell Mulcahy from a screenplay by Gregory Widen, Peter Bellwood, and Larry Ferguson. It stars Christopher Lambert, Roxanne Hart, Clancy Brown, and Sean Connery. The film chronicles the climax of an age-old war between immortal warriors, depicted through interwoven past and present-day storylines. It is the first film in the Highlander franchise." });
                Films.Add(new Film { Name="Mission Imposible: Fallout", DirectorName="Christopher McQuarrie", Genre="Action", Poster="~/Images/MIFallout.jpg", Date="2018", Description= "Mission: Impossible – Fallout is a 2018 American action spy film written and directed by Christopher McQuarrie. It is the sequel to Mission: Impossible – Rogue Nation (2015) and is the sixth installment in the Mission: Impossible film series. The film stars Tom Cruise as Ethan Hunt, with a supporting cast of Henry Cavill, Ving Rhames, Simon Pegg, Rebecca Ferguson, Angela Bassett, Sean Harris, Michelle Monaghan, and Alec Baldwin. " });
                Films.Add(new Film { Name="Oppenheimer", DirectorName= "Christopher Nolan", Genre= "Epic Biographical Thriller", Poster="~/Images/Oppenheimer.jpg", Date="2023", Description= "Oppenheimer (/ˈɒpənhaɪmər/ OP-ən-hy-mər) is a 2023 epic[5] biographical thriller film[6] written and directed by Christopher Nolan. Based on the 2005 biography American Prometheus by Kai Bird and Martin J. Sherwin, the film chronicles the career of Oppenheimer, with the story predominantly focusing on his studies, his direction of the Manhattan Project during World War II, and his eventual fall from grace due to his 1954 security hearing." });
                Films.Add(new Film { Name= "Legend of the Guardians: The Owls of Ga'Hoole", DirectorName= "Zack Snyder", Genre="Action-Adventure", Poster="~/Images/Owls.jpg", Date="2010", Description= "Legend of the Guardians: The Owls of Ga'Hoole is a 2010 3D computer-animated fantasy adventure film directed by Zack Snyder. Based on the Guardians of Ga'Hoole book series by Kathryn Lasky, the film was written by John Orloff and Emil Stern and features the voices of Helen Mirren, Geoffrey Rush, Jim Sturgess, Hugo Weaving, Emily Barclay, Abbie Cornish, Ryan Kwanten, Anthony LaPaglia, Miriam Margolyes, Sam Neill, Richard Roxburgh, and David Wenham." });
                Films.Add(new Film { Name= "The Hitchhiker's Guide to the Galaxy", DirectorName = "Garth Jennings", Genre = "Comedy", Poster= "~/Images/theHitchhikersGuide.jpg", Date="2005", Description= "The Hitchhiker's Guide to the Galaxy is a 2005 science fiction comedy film directed by Garth Jennings, based upon previous works in the media franchise of the same name, created by Douglas Adams. It stars Martin Freeman, Sam Rockwell, Mos Def, Zooey Deschanel, Bill Nighy, Anna Chancellor, John Malkovich, and the voices of Stephen Fry, Helen Mirren, Thomas Lennon, Richard Griffiths, Ian McNeice, Bill Bailey and Alan Rickman." });
                Films.Add(new Film { Name="The Killer", DirectorName= "David Fincher", Genre="Thriller", Poster="~/Images/TheKiller.jpg", Date="2023", Description= "The Killer is a 2023 American action thriller film directed by David Fincher from a screenplay by Andrew Kevin Walker. It is based on the French graphic novel series The Killer written by Alexis \"Matz\" Nolent and illustrated by Luc Jacamon.[5] The film stars Michael Fassbender in the title role, alongside Arliss Howard, Charles Parnell, Kerry O'Malley, Sala Baker, Sophie Charlotte, and Tilda Swinton in supporting roles." });
                Films.Add(new Film { Name = "Top Gun: Maverick", DirectorName = "Joseph Kosinski", Genre="Action", Poster="~/Images/TopGunMaverick.jpg", Date="2022", Description= "Top Gun: Maverick is a 2022 American action drama film directed by Joseph Kosinski and written by Ehren Kruger, Eric Warren Singer, and Christopher McQuarrie from stories by Peter Craig and Justin Marks. The film is a sequel to the 1986 film Top Gun. Tom Cruise reprises his starring role as the naval aviator Maverick. It also stars Miles Teller, Jennifer Connelly, Jon Hamm, Glen Powell, Lewis Pullman, Ed Harris and Val Kilmer, who reprises his role as Iceman." });
                SaveChanges();
            }
        }

    }
}
